name: CI-CD IoT

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/iot-api .

    - name: Push
      run: docker push ${{ secrets.DOCKER_USER }}/iot-api
    - name: Trigger Render Deploy
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
